# see https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD004 - Unordered list style
# We want to use dashes consistently everywhere
MD004:
  style: dash

# MD007 - Unordered list indentation
# We want to prevent conflict between apps involved to modify markdown
MD007:
  indent: 4

# MD013 - Line length
# We do not want to artificially limit line length
MD013: false

# MD033 - Inline HTML
MD033:
  allowed_elements:
    - details # there is no markdown equivalent for accordions
    - summary # there is no markdown equivalent for accordions
    - br
