default_install_hook_types:
  - pre-commit
  - commit-msg

default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            lazy-lock.json|
            lazyvim.json
          )$
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
        args:
          - --config
          - .markdownlint.yaml
          - --fix
        exclude: '^(CHANGELOG.md)$'

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.7.3'
    hooks:
      - id: editorconfig-checker
        exclude: |
          (?x)^(
            CHANGELOG.md|
            lazyvim.json
          )$

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua-system

  - repo: https://github.com/mrtazz/checkmake
    rev: 0.2.2
    hooks:
      - id: checkmake
